### PR TITLE
Fixed ResetCommand table isolation issues for postgresql and mssql

### PR DESCRIPTION
**Pull request by AnatolyRugalev**
Reset command does not work for mssql and postgresql without this change.

Cardinality checks could not be enabled back when table is already dropped.

See #50

### CODE REVIEW

**Comment by patrickbrouwers** [comment]
@guiwoda you are a bit more experienced with postgres than me, what's your thought on this?

**Comment by guiwoda** [comment]
Sorry @patrickbrouwers, I have no idea about this one. Does Doctrine have this kind of reset command on their side? Should we check and resync with what the ORM does?

**Comment by greabock** [comment]
any progress?

**Comment by guiwoda** [comment]
I'm sorry @greabock, I'm not on this anymore. I can help with issues, but I'm too far from the PHP ecosystem by now to contribute significantly.
Try to reach out to the community slack channel, see if there's any maintainer that can help you out with this PR in there!

**Pull request merged**
