### PR TITLE
Class Doctrine\DBAL\Migrations\AbstractMigration marked as deprecated…

### PR DESCRIPTION
**Pull request by smarley**
… in doctrine

### CODE REVIEW

**Comment by patrickbrouwers** [comment]
Since which version is it deprecated?

**Comment by smarley** [comment]
Since doctrine/migrations v1.8.0

**Comment by patrickbrouwers** [comment]
Can you update composer to make minimum migrations version higher

**Comment by smarley** [comment]
Yes i can, but i looked a little closer on doctrine/migrations 1.8 - it supports php version 7.1 and higher. When laravel-doctrine/migrations >=5.5.9. What is the best practice in suchlike situations? Release new version? Sorry for maybe silly questions, my first attempt to contribute

**Comment by patrickbrouwers** [comment]
I'll create a version 1.2 for this

**Comment by patrickbrouwers** [comment]
I have retargeted it to 1.2, you can also bump the php version to 7.1 and higher

**Comment by smarley** [comment]
Done! Checks failed because of php version mismatch

**Pull request merged**
