### PR TITLE
Giving a default phpunit config while letting people override it.

### PR DESCRIPTION
**Pull request by mikeSimonson**

### CODE REVIEW

**Comment by guiwoda** [comment]
Why would you do this? The project is not an application skeleton, `phpunit.xml` describes how the author expects the library to be tested.

**Comment by mikeSimonson** [comment]
If a dev wants to change the settings of phpunit by adding a plugin or something similar he doesn't need to edit the phpunit of the project and always see that file as modified. He just copy the dist file to the same filename without dist and phpunit will pick that one automatically.

**Comment by guiwoda** [comment]
Why would changing the configuration be a more frequent use case than using
the provided one? And why wouldn't the dev propose a PR with the changes,
if they are useful to the project?

I don't see this as being of any use to the project, I'd rather make it
easier for regular contributors to run tests than add flexibility to the
rare case when it's needed. I know other projects may need something like
this, but I feel this one is not the case.

**Comment by mikeSimonson** [comment]
Maybe I explained it the wrong way.
This PR won't change anything for someone that does not make any change to the phpunit config.
The way phpunit look for config is that he look for phpunit.xml and if it doesn't find anything it looks for phpunit.xml.dist.

The main reason for doing it like that is convenience for the dev in case of machine specific config. For example, I have a phpunit plug-in that tracks slow test. But because we all have machine that have different speed, it doesn't make any sense to use the same treshold to determine if  a test is slow or not. Furthermore I don't need to force everyone to use that plug-in and clutter their output of phpunit.

It's one example but you get the idea.

**Comment by guiwoda** [comment]
I stand corrected then! I didn't know about that!

```
--configuration, -c
Read configuration from XML file. See Appendix C for more details.

If phpunit.xml or phpunit.xml.dist (in that order) exist in the current working directory and --configuration is not used, the configuration will be automatically read from that file.
```

@mikeSimonson should we add `phpunit.xml` to the `.gitignore` as well?

**Comment by mikeSimonson** [comment]
It's much better explained in the documentation indeed.
Yes we should add phpunit.xml in the .gitignore . I forgot to do it. I can do it once you merge that PR.

**Pull request merged**
